---
# enable zeek
- name: enable Zeek Module
  ansible.builtin.shell: filebeat modules enable zeek
  notify: restart filebeat

- name: transfer zeek.yml
  ansible.builtin.copy:
    src: zeek.yml
    dest: /etc/filebeat/modules.d/zeek.yml
  notify: restart filebeat

# enable suricata
- name: enable Suricata
  ansible.builtin.shell: filebeat modules enable suricata
  notify: restart filebeat

- name: transfer suricata.yml
  ansible.builtin.copy:
    src: suricata.yml
    dest: /etc/filebeat/modules.d/suricata.yml
  notify: restart filebeat

# setup config with elasticsearch to configure pipeline
- name: copy filebeat.yml (with ES output)
  ansible.builtin.template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: "0644"
  vars:
    es_output: true
  notify: restart filebeat
  when: es_hosts is defined

- name: deploy pipelines to elasticsearch
  ansible.builtin.shell: filebeat setup --pipelines --modules zeek,suricata
  when: es_hosts is defined

# copy main config from template
- name: copy filebeat.yml 
  ansible.builtin.template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: "0644"
  vars:
    es_output: false
  notify: restart filebeat
